version: "3"
services:
  app:
    build: .
    container_name: finance-app
    command: bin/rails server --port 4000 --binding 0.0.0.0
    ports:
    - 4000:4000
    links:
    - db
    volumes:
    - .:/finance-app
    - gems:/gems
    tty: true
    stdin_open: true

  db:
    image: postgres:9.6
    container_name: finance-app-db
    volumes:
    - database:/var/lib/postgresql/data
    ports:
    - 4001:5432

volumes:
  database:
  gems:
